services:

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - portfolio
      - parcelenroute
    networks:
      - app-net

  portfolio:
    image: ghcr.io/harinderpartapsingh/portfolio-one-page:582fe60
    container_name: portfolio
    restart: unless-stopped
    networks:
      - app-net


  parcelenroute:
    image: ghcr.io/harryiscodingg/parcelenroute:ffe03b9
    container_name: parcelenroute
    restart: unless-stopped
    environment:
      - PORT=3000
    env_file:
      - ./env/parcelenroute.env
    networks:
      - app-net


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    networks:
      - app-net

networks:
  app-net:
    name: app-net